# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./rove_so_remote

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Export Release Timestamp
        run: |
          cd ..
          echo "APP_VERSION=release_$(date +'%Y-%m-%d_%H-%m-%S')" >> $GITHUB_ENV
      - name: set env
        run: |
          cd ..
          echo "RELEASE_NAME=$(date +'%Y-%m-%d_%H')" >> $GITHUB_ENV
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable" # or: 'beta' or 'master'
      - run: flutter --version
      - run: flutter pub get
      - name: Build Android App
        run: flutter build apk
      - name: Build iOS App
        run: |
          flutter build ios --no-codesign --export-method ad-hoc
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Release Apps
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.APP_VERSION }}
          name: ${{ env.RELEASE_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./rove_so_remote/build/app/outputs/apk/release/*.apk,./rove_so_remote/build/ios/iphoneos/app.ipa"
